worker_processes  1;
events { worker_connections  1024; }
http {
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    server {
        listen       8888;
        server_name  _;
        include D:/生产实习-大模型AI/项目/ai-agent-platform/backend/deploy/nginx/conf/app-*.conf;
    }
}
